name: tudiagnostico
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  flutter_svg: ^2.1.0
  sqflite: ^2.4.2
  path: ^1.9.1
  appwrite: ^15.0.0
  camera: ^0.11.1
  dio: ^5.0.0
  image: ^4.0.15
  intl: ^0.19.0
  uuid: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Nueva sección para resolver dependencias conflictivas
dependency_overrides:
  flutter_web_auth_2: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
